# Generated by Django 2.0.7 on 2018-07-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_name', models.CharField(max_length=100)),
                ('artifact_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_value', models.IntegerField(default=0)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=100)),
                ('set_arts_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SetBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_value', models.IntegerField(default=0)),
                ('bonus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Bonus')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Set')),
            ],
        ),
        migrations.AddField(
            model_name='artifactbonus',
            name='bonus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Bonus'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='art_bonus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Bonus'),
        ),
    ]
