# Generated by Django 2.0.7 on 2018-07-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bonus',
            name='race_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='artifacts.Race'),
            preserve_default=False,
        ),
    ]
