# Generated by Django 2.0.7 on 2018-07-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20180720_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.CharField(max_length=200),
        ),
    ]
