# Generated by Django 2.0.7 on 2018-07-20 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_auto_20180720_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='race_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='artifacts.Race'),
        ),
    ]
