# Generated by Django 2.0.7 on 2018-07-20 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_auto_20180720_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusAndRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='race_name',
        ),
        migrations.AddField(
            model_name='bonusandrace',
            name='bon_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Bonus'),
        ),
        migrations.AddField(
            model_name='bonusandrace',
            name='race_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artifacts.Race'),
        ),
    ]
