# Generated by Django 2.0.7 on 2018-07-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_auto_20180720_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bonusandrace',
            options={'ordering': ['bon_name', 'race_name']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='art_bonus_id',
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artifactbonus',
            name='bonus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.BonusAndRace'),
        ),
        migrations.AlterField(
            model_name='setbonus',
            name='bonus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.BonusAndRace'),
        ),
    ]
