# Generated by Django 2.0.7 on 2018-07-21 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_auto_20180721_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_level', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['bon_name']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['race_name']},
        ),
        migrations.AddField(
            model_name='artifact',
            name='set_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artifacts.Set'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artifacts.ArtifactLevel'),
        ),
    ]
