# Generated by Django 2.0.7 on 2018-07-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0008_auto_20180721_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactbonus',
            name='art_id',
        ),
        migrations.RemoveField(
            model_name='artifactbonus',
            name='bonus_id',
        ),
        migrations.RemoveField(
            model_name='setbonus',
            name='bonus_id',
        ),
        migrations.RemoveField(
            model_name='setbonus',
            name='set_id',
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_1', to='artifacts.BonusAndRace'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_1_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_2', to='artifacts.BonusAndRace'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_2_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_3', to='artifacts.BonusAndRace'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_3_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_4', to='artifacts.BonusAndRace'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_4_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_5', to='artifacts.BonusAndRace'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_5_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_6', to='artifacts.BonusAndRace'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_6_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_bonus_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='art_bonus_1', to='artifacts.BonusAndRace'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_bonus_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='art_bonus_2', to='artifacts.BonusAndRace'),
        ),
        migrations.DeleteModel(
            name='ArtifactBonus',
        ),
        migrations.DeleteModel(
            name='SetBonus',
        ),
    ]
