# Generated by Django 2.0.7 on 2018-07-21 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0009_auto_20180721_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact_level',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='artifacts.ArtifactLevel'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_3', to='artifacts.BonusAndRace'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_3_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_4', to='artifacts.BonusAndRace'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_4_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_5', to='artifacts.BonusAndRace'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_5_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_6', to='artifacts.BonusAndRace'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_6_value',
            field=models.IntegerField(null=True),
        ),
    ]
