# Generated by Django 2.0.7 on 2018-07-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0012_auto_20180721_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_name', 'set_arts_number']},
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_1_race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_1', to='artifacts.Race'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_2_race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_2', to='artifacts.Race'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_3_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_3', to='artifacts.Race'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_4_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_4', to='artifacts.Race'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_5_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_5', to='artifacts.Race'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_bonus_6_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_6', to='artifacts.Race'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_1', to='artifacts.Bonus'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_2', to='artifacts.Bonus'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_3', to='artifacts.Bonus'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_4', to='artifacts.Bonus'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_5', to='artifacts.Bonus'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_6', to='artifacts.Bonus'),
        ),
    ]
