# Generated by Django 2.0.7 on 2018-07-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0013_auto_20180721_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusandrace',
            name='bon_name',
        ),
        migrations.RemoveField(
            model_name='bonusandrace',
            name='race_name',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='set_owner',
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_bonus_1_race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='art_bonus_1_race', to='artifacts.Race'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_bonus_2_race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='art_bonus_2_race', to='artifacts.Race'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_art_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_art_1', to='artifacts.Artifact'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_art_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_art_2', to='artifacts.Artifact'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_art_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_art_3', to='artifacts.Artifact'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_art_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_art_4', to='artifacts.Artifact'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_art_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_art_5', to='artifacts.Artifact'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_art_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_art_6', to='artifacts.Artifact'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_bonus_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='art_bonus_1', to='artifacts.Bonus'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_bonus_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='art_bonus_2', to='artifacts.Bonus'),
        ),
        migrations.DeleteModel(
            name='BonusAndRace',
        ),
    ]
