# Generated by Django 2.0.7 on 2018-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0014_auto_20180721_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact_bonus_1_value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_bonus_2_value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_1_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_2_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_3_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_4_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_5_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_6_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
