# Generated by Django 2.0.7 on 2018-07-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0017_auto_20180721_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='artifact_bonus_1_value',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='artifact_bonus_2_value',
        ),
    ]
