# Generated by Django 2.0.7 on 2018-07-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0018_auto_20180721_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact_bonus_1_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_bonus_1_race', to='artifacts.Race'),
        ),
    ]
