# Generated by Django 2.0.7 on 2018-07-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0019_auto_20180721_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['artifact_number']},
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
