# Generated by Django 2.0.7 on 2018-07-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0020_auto_20180721_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_bonus_1_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_1_race', to='artifacts.Race'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_2_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_2_race', to='artifacts.Race'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_3_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_3_race', to='artifacts.Race'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_4_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_4_race', to='artifacts.Race'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_5_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_5_race', to='artifacts.Race'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_6_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_6_race', to='artifacts.Race'),
        ),
    ]
