# Generated by Django 2.0.7 on 2018-07-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0021_auto_20180721_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_bonus_1_value',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_2_value',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_3_value',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_4_value',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_5_value',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_bonus_6_value',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
