# Generated by Django 2.0.7 on 2018-07-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0026_auto_20180722_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_level',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='artifacts.ArtifactLevel'),
        ),
    ]
