# Generated by Django 2.0.7 on 2018-07-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0028_auto_20180731_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_tech_name', 'set_name', '-set_level_id']},
        ),
    ]
