# Generated by Django 2.0.7 on 2018-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0029_auto_20180731_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_name', '-set_level_id']},
        ),
    ]
