# Generated by Django 2.0.7 on 2018-08-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0030_auto_20180807_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_type', models.CharField(max_length=100)),
            ],
        ),
    ]
