# Generated by Django 2.0.7 on 2018-08-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0031_settype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settype',
            old_name='set_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='set',
            name='set_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_type', to='artifacts.SetType'),
        ),
    ]
