# Generated by Django 2.0.7 on 2018-08-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0032_auto_20180816_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['-set_type_order', 'set_name', 'set_tech_name', '-set_level_id']},
        ),
        migrations.AlterModelOptions(
            name='settype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='set',
            name='set_type_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_type_order', to='artifacts.SetType'),
        ),
        migrations.AddField(
            model_name='settype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
